#!/usr/bin/env python3
"""
Qwen Worker - Production Data Fetcher
Fetches and formats price data with validation
"""

import os
import sys
import json
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

WORKSPACE = Path("/Users/thekhemist/.openclaw/workspace")

# Watchlist - token addresses to monitor
WATCHLIST = {
    "BENJI": "0xBC45647eA894030a4E9801Ec03479739FA2485F0",  # Basenji on Base
    "AIGHT": "0xAf11B23a708bee537C44F3d85C2e0fd93E508b07",  # AIGHT on Base
}

def fetch_dexscreener(token_address):
    """Fetch data from DexScreener API with error handling"""
    url = f"https://api.dexscreener.com/latest/dex/tokens/{token_address}"
    
    try:
        req = urllib.request.Request(
            url,
            headers={
                'User-Agent': 'Qwen-Worker/1.0',
                'Accept': 'application/json'
            }
        )
        
        with urllib.request.urlopen(req, timeout=10) as response:
            if response.status != 200:
                return {"error": f"HTTP {response.status}"}
            
            data = json.loads(response.read().decode('utf-8'))
            return data
            
    except urllib.error.HTTPError as e:
        return {"error": f"HTTP Error {e.code}: {e.reason}"}
    except urllib.error.URLError as e:
        return {"error": f"URL Error: {e.reason}"}
    except json.JSONDecodeError:
        return {"error": "Invalid JSON response"}
    except Exception as e:
        return {"error": f"Exception: {str(e)}"}

def extract_price_data(api_response):
    """Extract and validate price data from API response"""
    if "error" in api_response:
        return None
    
    try:
        pairs = api_response.get("pairs", [])
        if not pairs:
            return None
        
        # Get first pair (usually most liquid)
        pair = pairs[0]
        
        return {
            "price_usd": float(pair.get("priceUsd", 0)),
            "volume_24h": float(pair.get("volume", {}).get("h24", 0)),
            "price_change_24h": float(pair.get("priceChange", {}).get("h24", 0)),
            "liquidity_usd": float(pair.get("liquidity", {}).get("usd", 0)),
            "fdv": float(pair.get("fdv", 0)),
            "dex": pair.get("dexId", "unknown"),
            "timestamp": datetime.now().isoformat()
        }
    except (ValueError, TypeError) as e:
        return {"error": f"Data validation failed: {e}"}

def validate_price_data(data):
    """Validate extracted price data"""
    if not data:
        return False, "No data"
    
    if "error" in data:
        return False, data["error"]
    
    # Sanity checks
    if data["price_usd"] <= 0:
        return False, f"Invalid price: {data['price_usd']}"
    
    if data["price_usd"] > 1000000:  # $1M per token is suspicious
        return False, f"Suspicious price: {data['price_usd']}"
    
    if abs(data["price_change_24h"]) > 1000:  # 1000% change is suspicious
        return False, f"Suspicious change: {data['price_change_24h']}%"
    
    return True, "Valid"

def generate_report(token_data):
    """Generate formatted report"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = f"""# Qwen Worker Report - Price Data
**Task:** Token Price Monitor  
**Time:** {timestamp}  
**Status:** ✅ Complete

## Price Data
| Token | Price (USD) | 24h Change | Volume (24h) | Liquidity | DEX |
|-------|-------------|------------|--------------|-----------|-----|
"""
    
    for token, data in token_data.items():
        if "error" in data or not data.get("valid"):
            report += f"| {token} | ⚠️ ERROR | - | - | - | - |\n"
        else:
            report += f"| {token} | ${data['price_usd']:.6f} | {data['price_change_24h']:+.2f}% | ${data['volume_24h']:,.0f} | ${data['liquidity_usd']:,.0f} | {data['dex']} |\n"
    
    report += f"""
## Raw Data (JSON)
```json
{json.dumps(token_data, indent=2, default=str)}
```

## Validation Results
"""
    
    for token, data in token_data.items():
        if data.get("valid"):
            report += f"- ✅ {token}: {data.get('validation_msg', 'OK')}\n"
        else:
            report += f"- ⚠️ {token}: {data.get('validation_msg', 'ERROR')}\n"
    
    report += """
## Action Required
- [ ] Review any validation errors
- [ ] Check suspicious price movements
- [ ] Khem to verify if anomalies detected

---
*Report generated by Qwen Worker*
*Validation: ENABLED*
"""
    
    return report

def save_report(report):
    """Save report to file"""
    report_dir = WORKSPACE / "memory" / "qwen-worker" / "data-reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    report_file = report_dir / f"price-data-{timestamp}.md"
    
    with open(report_file, 'w') as f:
        f.write(report)
    
    return report_file

def main():
    """Main entry point"""
    print(f"[{datetime.now()}] Qwen Worker: Fetching price data...")
    
    token_data = {}
    
    for token_name, token_address in WATCHLIST.items():
        print(f"  Fetching {token_name}...")
        
        # Fetch from API
        api_response = fetch_dexscreener(token_address)
        
        # Extract data
        extracted = extract_price_data(api_response)
        
        # Validate
        if extracted:
            is_valid, msg = validate_price_data(extracted)
            extracted["valid"] = is_valid
            extracted["validation_msg"] = msg
            token_data[token_name] = extracted
        else:
            token_data[token_name] = {
                "valid": False,
                "validation_msg": "No data extracted",
                "raw_response": str(api_response)[:500]
            }
    
    # Generate and save report
    report = generate_report(token_data)
    report_file = save_report(report)
    
    print(f"[{datetime.now()}] Report saved: {report_file}")
    
    # Summary
    print("\n=== PRICE DATA SUMMARY ===")
    for token, data in token_data.items():
        if data.get("valid"):
            print(f"{token}: ${data['price_usd']:.6f} ({data['price_change_24h']:+.2f}%)")
        else:
            print(f"{token}: ⚠️ {data.get('validation_msg', 'ERROR')}")
    print("==========================\n")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
