#!/usr/bin/env python3
"""
Qwen Worker - Heartbeat Task
Monitors active-tasks.md and reports status
Runs every 30 minutes via cron
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

# Add workspace to path
WORKSPACE = Path("/Users/thekhemist/.openclaw/workspace")
sys.path.insert(0, str(WORKSPACE))

def read_file(filepath):
    """Safely read a file"""
    try:
        with open(filepath, 'r') as f:
            return f.read()
    except FileNotFoundError:
        return None
    except Exception as e:
        return f"[ERROR: {e}]"

def check_active_tasks():
    """Read and summarize active-tasks.md"""
    tasks_path = WORKSPACE / "active-tasks.md"
    content = read_file(tasks_path)
    
    if content is None or content.startswith("[ERROR"):
        return {
            "timestamp": datetime.now().isoformat(),
            "critical_tasks": 0,
            "high_priority": 0,
            "medium_priority": 0,
            "blocked_items": 0,
            "raw_snippet": f"[FILE NOT FOUND: {content}]"
        }
    
    # Count task statuses
    critical = content.count("Priority: CRITICAL")
    high = content.count("Priority: HIGH")
    medium = content.count("Priority: medium")
    blocked = content.count("Status: Chrome open") + content.count("Status: waiting")
    
    summary = {
        "timestamp": datetime.now().isoformat(),
        "critical_tasks": critical,
        "high_priority": high,
        "medium_priority": medium,
        "blocked_items": blocked,
        "raw_snippet": content[:2000]  # First 2000 chars
    }
    
    return summary

def check_recent_files():
    """Check for new files in last 30 minutes"""
    memory_dir = WORKSPACE / "memory" / "daily"
    recent_files = []
    
    if memory_dir.exists():
        for file in memory_dir.iterdir():
            if file.is_file():
                mtime = datetime.fromtimestamp(file.stat().st_mtime)
                age_minutes = (datetime.now() - mtime).total_seconds() / 60
                if age_minutes < 30:
                    recent_files.append({
                        "file": file.name,
                        "modified": mtime.isoformat(),
                        "age_minutes": int(age_minutes)
                    })
    
    return recent_files

def generate_report():
    """Generate heartbeat report"""
    tasks_summary = check_active_tasks()
    recent_files = check_recent_files()
    
    report = f"""# Qwen Worker Report - Heartbeat Check
**Task:** Active Tasks Monitor  
**Time:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Status:** ✅ Complete

## Task Summary
| Priority | Count |
|----------|-------|
| CRITICAL | {tasks_summary.get('critical_tasks', 0)} |
| HIGH | {tasks_summary.get('high_priority', 0)} |
| MEDIUM | {tasks_summary.get('medium_priority', 0)} |
| **BLOCKED** | **{tasks_summary.get('blocked_items', 0)}** |

## Recent Activity (Last 30 min)
"""
    
    if recent_files:
        report += "| File | Age (min) |\n|------|-----------|\n"
        for f in recent_files:
            report += f"| {f['file']} | {f['age_minutes']} |\n"
    else:
        report += "_No new files in last 30 minutes_\n"
    
    report += f"""
## Raw Task Snippet
```
{tasks_summary.get('raw_snippet', '[No content]')[:1500]}
```

## Action Required
- [ ] Khem to review any CRITICAL items
- [ ] Check blocked items for unblocking
- [ ] {'New files to review' if recent_files else 'No new files'}

---
*Report generated by Qwen Worker (ollama/qwen3:8b)*
*Cost: $0.00 (local inference)*
"""
    
    return report

def save_report(report):
    """Save report to file"""
    report_dir = WORKSPACE / "memory" / "qwen-worker" / "heartbeat-reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    report_file = report_dir / f"heartbeat-{timestamp}.md"
    
    with open(report_file, 'w') as f:
        f.write(report)
    
    return report_file

def main():
    """Main entry point"""
    print(f"[{datetime.now()}] Qwen Worker: Starting heartbeat check...")
    
    # Generate report
    report = generate_report()
    
    # Save to file
    report_file = save_report(report)
    print(f"[{datetime.now()}] Report saved: {report_file}")
    
    # Also print summary
    print("\n=== HEARTBEAT SUMMARY ===")
    tasks_summary = check_active_tasks()
    print(f"CRITICAL: {tasks_summary.get('critical_tasks', 0)}")
    print(f"HIGH: {tasks_summary.get('high_priority', 0)}")
    print(f"BLOCKED: {tasks_summary.get('blocked_items', 0)}")
    print("========================\n")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
